apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gcactivities
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gcactivities
subjects:
  - kind: ServiceAccount
    name: jx-gcactivities
    namespace: {{ .Release.Namespace }}
